# Generated by Django 2.1.2 on 2018-10-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gossips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gossip',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
